# Generated by Django 4.1.3 on 2022-12-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_game_genre_list',
            field=models.ManyToManyField(blank=True, to='games.gamegenre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_game_list',
            field=models.ManyToManyField(blank=True, to='games.game'),
        ),
    ]
