# Generated by Django 4.1.3 on 2022-12-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre_list',
            field=models.ManyToManyField(related_name='games', to='games.gamegenre'),
        ),
    ]
